services:
  - type: web
    name: acronym-extractor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BING_SUBSCRIPTION_KEY
        sync: false
      - key: BING_ENDPOINT
        value: https://api.bing.microsoft.com/v7.0/search
      - key: WEB_MAX_CANDIDATES
        value: "5"
